### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by BlackYoup** [dblock/syntax#5]
Hi,

Can you please release 1.2.1 with this commit ? https://github.com/dblock/syntax/commit/22430510b9662edd64e3792c560629daf8aebc82

As this 1.2.0 version is quite broken without the `require set`

Thanks !

**Comment by dblock** [comment]
It took a bit more time than I thought it would, had to fight Ruby+Rubygems :) See https://github.com/dblock/syntax/commit/c12aa71d7ce0333b70aaa75e903850aee3c44930

1.2.1 has been relased

**Comment by BlackYoup** [comment]
Thank you !
