### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [dblock/syntax#8]
Following https://github.com/dblock/syntax/blob/master/RELEASING.rdoc. 

@pat Want to do it after #6 is merged? What's your Rubygems email, I'll add you to owners?

**Comment by pat** [comment]
Sure, happy to sort this out - my email is pat at freelancing-gods dot com.

**Comment by pat** [comment]
Also, given there's no functionality change in this gem - what I've added is essentially a bug fix - I'm presuming this version will be 1.2.2, but let me know if you think it should be 1.3.0 instead.

**Comment by dblock** [comment]
Added you. I think 1.2.2 is fine.

**Comment by pat** [comment]
Done 👍

**Comment by dblock** [comment]
🎸
